# Generated by Django 4.0.3 on 2022-07-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('img1', models.ImageField(upload_to='pic')),
                ('img2', models.ImageField(upload_to='pic')),
                ('img3', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=200)),
                ('des', models.TextField()),
                ('timings', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
