# Generated by Django 4.0.3 on 2022-09-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=12)),
                ('msg', models.TextField()),
            ],
        ),
    ]
