# Generated by Django 4.0.3 on 2022-09-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactus',
        ),
    ]
