# Generated by Django 4.0.3 on 2022-09-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_contact_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.TextField(),
        ),
    ]
