# Generated by Django 4.0.3 on 2022-09-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contactus_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='printpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inv', models.CharField(max_length=100)),
                ('urname', models.CharField(max_length=100)),
                ('checkin', models.CharField(max_length=100)),
                ('checkot', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
    ]
