# Generated by Django 4.0.3 on 2022-09-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_printpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printpage',
            old_name='name',
            new_name='booking',
        ),
    ]
